# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'citystars_react_native' do
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'FBSDKLoginKit'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
end
